
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('N20FAL','Mercedes','E230','Diesel',1);
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('CK20PPO','KIA','eNiro','Petrol',2);
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('CK19CVS','VW','ESPRO','Diesel',3);
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('CK18CLD','BMW','380i','Diesel',1);
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('SW17JKD','AUDI','Quatro 360','Petrol',2);
INSERT INTO Vehicle(REGISTRATION_NUMBER,MAKE,MODEL, FUEL_TYPE,VEHICLE_TYPE_ID) VALUES ('CK19JWD','Mercedes','XMAN','Diesel',3);

INSERT INTO  DAILY_RATE_LOOKUP(ID, VEHICLE_TYPE, PRICE_PER_DAY) VALUES(1, 'Small',25);
INSERT INTO  DAILY_RATE_LOOKUP(ID, VEHICLE_TYPE, PRICE_PER_DAY) VALUES(2, 'Estate',35);
INSERT INTO  DAILY_RATE_LOOKUP(ID, VEHICLE_TYPE, PRICE_PER_DAY) VALUES(3, 'Van',50);

INSERT INTO CUSTOMER(NAME,TYPE) VALUES ('Nofal Elias','individual');
INSERT INTO CUSTOMER(NAME,TYPE) VALUES ('Rollex Invovations','company');