CREATE TABLE Vehicle (
         REGISTRATION_NUMBER VARCHAR(50) PRIMARY KEY,
         MAKE VARCHAR(20),
         MODEL VARCHAR(30),
         FUEL_TYPE VARCHAR(20),
         VEHICLE_TYPE_ID INT);

CREATE TABLE DAILY_RATE_LOOKUP (
         ID INT AUTO_INCREMENT  PRIMARY KEY,
         VEHICLE_TYPE VARCHAR(50),
         PRICE_PER_DAY NUMERIC(6,2)
         );

CREATE TABLE CUSTOMER (
         ID INT AUTO_INCREMENT  PRIMARY KEY,
         NAME VARCHAR(100),
         TYPE VARCHAR(50)
         );